<a href="https://colab.research.google.com/github/Nikhilsankhyan0/Agrisheild-AI/blob/main/AgriShield_preporcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('/content/drive/MyDrive/agrishield_ai_loan_dataset.csv')
df.shape

(20040, 60)

In [88]:
df.head()

,Farmer_ID,Application_Date,Age,Gender,Education_Level,Marital_Status,Family_Size,Dependents,Farming_Experience_Years,State,...,EMI,Income_Stability_Index,Farm_Productivity_Index,Climate_Risk_Index,Financial_Health_Index,Loan_Affordability_Index,Asset_Strength_Index,Overall_Risk_Factor,Risk_Score,Loan_Status
0,AGR117544,23-06-2023,53.0,Male,Higher Secondary,Married,8.0,4.0,NaN,Kerala,...,4506.78,40.7,52.5,65.4,57.7,65.5,48.5,73.2,40.6,Approved with Conditions
1,AGR103888,02-10-2022,39.0,Female,Illiterate,Married,8.0,3.0,21.0,Jharkhand,...,951.98,55.4,53.3,35.1,70.3,72.2,43.7,52.0,54.7,Approved
2,AGR112882,17-07-2024,27.0,Male,Secondary,Married,8.0,3.0,9.0,Madhya Pradesh,...,10895.49,50.5,44.4,48.4,50.3,41.5,46.8,95.8,22.7,Rejected
3,AGR108149,26-07-2024,41.0,Male,Post Graduate,Married,6.0,3.0,22.0,Haryana,...,524.61,52.3,56.5,49.5,0.0,13.1,46.2,100.0,20.8,Rejected
4,AGR115346,24-04-2022,33.0,Male,Primary,Married,NaN,3.0,12.0,Gujarat,...,1220.20,39.6,32.7,47.3,59.6,79.5,49.9,65.8,34.6,Approved with Conditions

In [89]:
df.tail()

,Farmer_ID,Application_Date,Age,Gender,Education_Level,Marital_Status,Family_Size,Dependents,Farming_Experience_Years,State,...,EMI,Income_Stability_Index,Farm_Productivity_Index,Climate_Risk_Index,Financial_Health_Index,Loan_Affordability_Index,Asset_Strength_Index,Overall_Risk_Factor,Risk_Score,Loan_Status
20035,AGR117677,21-04-2021,46.0,Male,Primary,Married,6.0,3.0,29.0,Tamil Nadu,...,1664.33,50.5,61.4,52.8,14.8,19.1,NaN,100.0,16.1,Rejected
20036,AGR104023,17-06-2021,45.0,Male,Secondary,Married,8.0,4.0,24.0,Chhattisgarh,...,5595.50,63.7,61.7,0.0,56.4,51.8,59.4,54.0,31.8,Rejected
20037,AGR107259,04-05-2022,31.0,Male,Higher Secondary,Married,5.0,3.0,10.0,Punjab,...,958.36,54.1,59.4,43.5,65.8,66.8,51.1,67.9,52.9,Approved
20038,AGR103775,05-11-2023,43.0,Male,Graduate,Married,5.0,2.0,25.0,Maharashtra,...,10841.73,49.5,50.7,19.5,64.4,0.0,41.7,74.5,38.5,Approved with Conditions
20039,AGR110137,05-12-2025,66.0,Male,Secondary,Married,9.0,3.0,51.0,Telangana,...,42816.16,60.0,54.6,35.5,38.4,42.4,49.8,91.6,26.1,Rejected

In [90]:
print("duplicates :",df.duplicated().sum())

duplicates : 0

In [91]:
print("No. of columns :",len(df.columns))
print("No. of rows :",len(df))

No. of columns : 60
No. of rows : 20040

In [92]:
print(df.columns.tolist())

['Farmer_ID', 'Application_Date', 'Age', 'Gender', 'Education_Level', 'Marital_Status', 'Family_Size', 'Dependents', 'Farming_Experience_Years', 'State', 'District', 'Farm_Size_Acres', 'Land_Ownership', 'Soil_Type', 'Soil_Quality_Index', 'Irrigation_Availability', 'Primary_Crop', 'Secondary_Crop', 'Annual_Rainfall_mm', 'Average_Temperature_C', 'Humidity_Percent', 'Flood_Risk', 'Drought_Risk', 'Cyclone_Risk', 'Pest_Risk', 'Weather_Risk_Index', 'Climate_Zone', 'Average_Yield_Last3Years_TonsPerAcre', 'Crop_Insurance', 'Government_Subsidy', 'MSP_Eligible', 'Annual_Farm_Income', 'Annual_Farm_Expenses', 'Tractor_Ownership', 'Farm_Equipment_Value', 'Livestock_Count', 'Asset_Value', 'Liability_Value', 'Savings', 'Bank_Balance', 'Credit_Score', 'Existing_Loan_Count', 'Existing_Loan_Amount', 'Previous_Default', 'Repayment_History_Score', 'Debt_to_Income_Ratio', 'Loan_Amount_Requested', 'Loan_Purpose', 'Interest_Rate_Percent', 'Loan_Tenure_Months', 'EMI', 'Income_Stability_Index', 'Farm_Productivity_Index', 'Climate_Risk_Index', 'Financial_Health_Index', 'Loan_Affordability_Index', 'Asset_Strength_Index', 'Overall_Risk_Factor', 'Risk_Score', 'Loan_Status']

verify structure

In [93]:

print("total columns :",len(df.columns))
for i ,col in enumerate(df.columns,start=1):
  print(i," -> ",col)

total columns : 60
1  ->  Farmer_ID
2  ->  Application_Date
3  ->  Age
4  ->  Gender
5  ->  Education_Level
6  ->  Marital_Status
7  ->  Family_Size
8  ->  Dependents
9  ->  Farming_Experience_Years
10  ->  State
11  ->  District
12  ->  Farm_Size_Acres
13  ->  Land_Ownership
14  ->  Soil_Type
15  ->  Soil_Quality_Index
16  ->  Irrigation_Availability
17  ->  Primary_Crop
18  ->  Secondary_Crop
19  ->  Annual_Rainfall_mm
20  ->  Average_Temperature_C
21  ->  Humidity_Percent
22  ->  Flood_Risk
23  ->  Drought_Risk
24  ->  Cyclone_Risk
25  ->  Pest_Risk
26  ->  Weather_Risk_Index
27  ->  Climate_Zone
28  ->  Average_Yield_Last3Years_TonsPerAcre
29  ->  Crop_Insurance
30  ->  Government_Subsidy
31  ->  MSP_Eligible
32  ->  Annual_Farm_Income
33  ->  Annual_Farm_Expenses
34  ->  Tractor_Ownership
35  ->  Farm_Equipment_Value
36  ->  Livestock_Count
37  ->  Asset_Value
38  ->  Liability_Value
39  ->  Savings
40  ->  Bank_Balance
41  ->  Credit_Score
42  ->  Existing_Loan_Count
43  ->  Existing_Loan_Amount
44  ->  Previous_Default
45  ->  Repayment_History_Score
46  ->  Debt_to_Income_Ratio
47  ->  Loan_Amount_Requested
48  ->  Loan_Purpose
49  ->  Interest_Rate_Percent
50  ->  Loan_Tenure_Months
51  ->  EMI
52  ->  Income_Stability_Index
53  ->  Farm_Productivity_Index
54  ->  Climate_Risk_Index
55  ->  Financial_Health_Index
56  ->  Loan_Affordability_Index
57  ->  Asset_Strength_Index
58  ->  Overall_Risk_Factor
59  ->  Risk_Score
60  ->  Loan_Status

In [94]:
print(df.dtypes)

Farmer_ID                                object
Application_Date                         object
Age                                     float64
Gender                                   object
Education_Level                          object
Marital_Status                           object
Family_Size                             float64
Dependents                              float64
Farming_Experience_Years                float64
State                                    object
District                                 object
Farm_Size_Acres                         float64
Land_Ownership                           object
Soil_Type                                object
Soil_Quality_Index                      float64
Irrigation_Availability                  object
Primary_Crop                             object
Secondary_Crop                           object
Annual_Rainfall_mm                      float64
Average_Temperature_C                   float64
Humidity_Percent                        float64
Flood_Risk                               object
Drought_Risk                             object
Cyclone_Risk                             object
Pest_Risk                                object
Weather_Risk_Index                      float64
Climate_Zone                             object
Average_Yield_Last3Years_TonsPerAcre    float64
Crop_Insurance                           object
Government_Subsidy                       object
MSP_Eligible                             object
Annual_Farm_Income                      float64
Annual_Farm_Expenses                    float64
Tractor_Ownership                        object
Farm_Equipment_Value                    float64
Livestock_Count                         float64
Asset_Value                             float64
Liability_Value                         float64
Savings                                 float64
Bank_Balance                            float64
Credit_Score                            float64
Existing_Loan_Count                     float64
Existing_Loan_Amount                    float64
Previous_Default                         object
Repayment_History_Score                 float64
Debt_to_Income_Ratio                    float64
Loan_Amount_Requested                   float64
Loan_Purpose                             object
Interest_Rate_Percent                   float64
Loan_Tenure_Months                      float64
EMI                                     float64
Income_Stability_Index                  float64
Farm_Productivity_Index                 float64
Climate_Risk_Index                      float64
Financial_Health_Index                  float64
Loan_Affordability_Index                float64
Asset_Strength_Index                    float64
Overall_Risk_Factor                     float64
Risk_Score                              float64
Loan_Status                              object
dtype: object

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20040 entries, 0 to 20039
Data columns (total 60 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Farmer_ID                             20040 non-null  object
 1   Application_Date                      20040 non-null  object
 2   Age                                   19140 non-null  float64
 3   Gender                                19144 non-null  object
 4   Education_Level                       19432 non-null  object
 5   Marital_Status                        18889 non-null  object
 6   Family_Size                           19455 non-null  float64
 7   Dependents                            19549 non-null  float64
 8   Farming_Experience_Years              19267 non-null  float64
 9   State                                 19482 non-null  object
 10  District                              19378 non-null  object
 11  Farm_Size_Acres                       19304 non-null  float64
 12  Land_Ownership                        18963 non-null  object
 13  Soil_Type                             18952 non-null  object
 14  Soil_Quality_Index                    18902 non-null  float64
 15  Irrigation_Availability               19135 non-null  object
 16  Primary_Crop                          19333 non-null  object
 17  Secondary_Crop                        19290 non-null  object
 18  Annual_Rainfall_mm                    19614 non-null  float64
 19  Average_Temperature_C                 19065 non-null  float64
 20  Humidity_Percent                      19455 non-null  float64
 21  Flood_Risk                            19429 non-null  object
 22  Drought_Risk                          19318 non-null  object
 23  Cyclone_Risk                          18852 non-null  object
 24  Pest_Risk                             19527 non-null  object
 25  Weather_Risk_Index                    19407 non-null  float64
 26  Climate_Zone                          19013 non-null  object
 27  Average_Yield_Last3Years_TonsPerAcre  18915 non-null  float64
 28  Crop_Insurance                        18849 non-null  object
 29  Government_Subsidy                    19186 non-null  object
 30  MSP_Eligible                          19551 non-null  object
 31  Annual_Farm_Income                    19034 non-null  float64
 32  Annual_Farm_Expenses                  19098 non-null  float64
 33  Tractor_Ownership                     19417 non-null  object
 34  Farm_Equipment_Value                  19006 non-null  float64
 35  Livestock_Count                       19640 non-null  float64
 36  Asset_Value                           19635 non-null  float64
 37  Liability_Value                       19041 non-null  float64
 38  Savings                               19244 non-null  float64
 39  Bank_Balance                          19496 non-null  float64
 40  Credit_Score                          19387 non-null  float64
 41  Existing_Loan_Count                   19286 non-null  float64
 42  Existing_Loan_Amount                  19280 non-null  float64
 43  Previous_Default                      19479 non-null  object
 44  Repayment_History_Score               19240 non-null  float64
 45  Debt_to_Income_Ratio                  19257 non-null  float64
 46  Loan_Amount_Requested                 19023 non-null  float64
 47  Loan_Purpose                          19041 non-null  object
 48  Interest_Rate_Percent                 19102 non-null  float64
 49  Loan_Tenure_Months                    19036 non-null  float64
 50  EMI                                   18961 non-null  float64
 51  Income_Stability_Index                19293 non-null  float64
 52  Farm_Productivity_Index               19060 non-null  float64
 53  Climate_Risk_Index                    19414 non-null  float64
 54  Financial_Health_Index                19361 non-null  float64
 55  Loan_Affordability_Index              19511 non-null  float64
 56  Asset_Strength_Index                  19018 non-null  float64
 57  Overall_Risk_Factor                   19248 non-null  float64
 58  Risk_Score                            20040 non-null  float64
 59  Loan_Status                           20040 non-null  object
dtypes: float64(36), object(24)
memory usage: 9.2+ MB

In [96]:
structure_audit=pd.DataFrame({
    'columns':df.columns,
    'data_type':df.dtypes.astype(str),
    'non_null_values':df.notna().sum().values,
    'missing_values':df.isna().sum().values,
    'unique_values':df.nunique().values
})
structure_audit

,columns,data_type,non_null_values,missing_values,unique_values
Farmer_ID,Farmer_ID,object,20040,0,20040
Application_Date,Application_Date,object,20040,0,1680
Age,Age,float64,19140,900,58
Gender,Gender,object,19144,896,3
Education_Level,Education_Level,object,19432,608,6
Marital_Status,Marital_Status,object,18889,1151,4
Family_Size,Family_Size,float64,19455,585,12
Dependents,Dependents,float64,19549,491,8
Farming_Experience_Years,Farming_Experience_Years,float64,19267,773,56
State,State,object,19482,558,20
District,District,object,19378,662,100
Farm_Size_Acres,Farm_Size_Acres,float64,19304,736,2869
Land_Ownership,Land_Ownership,object,18963,1077,4
Soil_Type,Soil_Type,object,18952,1088,11
Soil_Quality_Index,Soil_Quality_Index,float64,18902,1138,801
Irrigation_Availability,Irrigation_Availability,object,19135,905,2
Primary_Crop,Primary_Crop,object,19333,707,17
Secondary_Crop,Secondary_Crop,object,19290,750,24
Annual_Rainfall_mm,Annual_Rainfall_mm,float64,19614,426,11905
Average_Temperature_C,Average_Temperature_C,float64,19065,975,343
Humidity_Percent,Humidity_Percent,float64,19455,585,647
Flood_Risk,Flood_Risk,object,19429,611,2
Drought_Risk,Drought_Risk,object,19318,722,2
Cyclone_Risk,Cyclone_Risk,object,18852,1188,2
Pest_Risk,Pest_Risk,object,19527,513,3
Weather_Risk_Index,Weather_Risk_Index,float64,19407,633,967
Climate_Zone,Climate_Zone,object,19013,1027,4
Average_Yield_Last3Years_TonsPerAcre,Average_Yield_Last3Years_TonsPerAcre,float64,18915,1125,475
Crop_Insurance,Crop_Insurance,object,18849,1191,2
Government_Subsidy,Government_Subsidy,object,19186,854,2
MSP_Eligible,MSP_Eligible,object,19551,489,2
Annual_Farm_Income,Annual_Farm_Income,float64,19034,1006,16796
Annual_Farm_Expenses,Annual_Farm_Expenses,float64,19098,942,18011
Tractor_Ownership,Tractor_Ownership,object,19417,623,2
Farm_Equipment_Value,Farm_Equipment_Value,float64,19006,1034,18483
Livestock_Count,Livestock_Count,float64,19640,400,14
Asset_Value,Asset_Value,float64,19635,405,19449
Liability_Value,Liability_Value,float64,19041,999,18515
Savings,Savings,float64,19244,796,16816
Bank_Balance,Bank_Balance,float64,19496,544,13127
Credit_Score,Credit_Score,float64,19387,653,412
Existing_Loan_Count,Existing_Loan_Count,float64,19286,754,7
Existing_Loan_Amount,Existing_Loan_Amount,float64,19280,760,9985
Previous_Default,Previous_Default,object,19479,561,2
Repayment_History_Score,Repayment_History_Score,float64,19240,800,814
Debt_to_Income_Ratio,Debt_to_Income_Ratio,float64,19257,783,2825
Loan_Amount_Requested,Loan_Amount_Requested,float64,19023,1017,15122
Loan_Purpose,Loan_Purpose,object,19041,999,10
Interest_Rate_Percent,Interest_Rate_Percent,float64,19102,938,645
Loan_Tenure_Months,Loan_Tenure_Months,float64,19036,1004,8
EMI,EMI,float64,18961,1079,17959
Income_Stability_Index,Income_Stability_Index,float64,19293,747,641
Farm_Productivity_Index,Farm_Productivity_Index,float64,19060,980,743
Climate_Risk_Index,Climate_Risk_Index,float64,19414,626,929
Financial_Health_Index,Financial_Health_Index,float64,19361,679,804
Loan_Affordability_Index,Loan_Affordability_Index,float64,19511,529,907
Asset_Strength_Index,Asset_Strength_Index,float64,19018,1022,359
Overall_Risk_Factor,Overall_Risk_Factor,float64,19248,792,616
Risk_Score,Risk_Score,float64,20040,0,714
Loan_Status,Loan_Status,object,20040,0,3

In [97]:
numerical_cols=df.select_dtypes(
    include=['int64','float64']
)

print(numerical_cols)

        Age  Family_Size  Dependents  Farming_Experience_Years  \
0      53.0          8.0         4.0                       NaN
1      39.0          8.0         3.0                      21.0
2      27.0          8.0         3.0                       9.0
3      41.0          6.0         3.0                      22.0
4      33.0          NaN         3.0                      12.0
...     ...          ...         ...                       ...
20035  46.0          6.0         3.0                      29.0
20036  45.0          8.0         4.0                      24.0
20037  31.0          5.0         3.0                      10.0
20038  43.0          5.0         2.0                      25.0
20039  66.0          9.0         3.0                      51.0

       Farm_Size_Acres  Soil_Quality_Index  Annual_Rainfall_mm  \
0                 5.21                58.7              2766.9
1                 2.09                57.3              1559.8
2                10.00                73.5               778.5
3                 1.27                70.2               705.5
4                16.91                56.0               824.9
...                ...                 ...                 ...
20035             1.31                76.1               872.0
20036             4.84                57.5              1268.1
20037             1.36                72.5               701.0
20038             1.02                69.7              1344.3
20039            26.91                67.1               602.6

       Average_Temperature_C  Humidity_Percent  Weather_Risk_Index  ...  \
0                       29.5              64.1                61.9  ...
1                       19.2              40.9                32.8  ...
2                       27.6              43.6                56.2  ...
3                       30.0              31.3                49.8  ...
4                       22.7              33.5                50.3  ...
...                      ...               ...                 ...  ...
20035                   31.5              29.4                53.2  ...
20036                   24.0              39.3                 0.8  ...
20037                   26.3              54.0                45.7  ...
20038                   28.4              41.1                29.0  ...
20039                   31.0              33.9                34.5  ...

       Loan_Tenure_Months       EMI  Income_Stability_Index  \
0                    60.0   4506.78                    40.7
1                    24.0    951.98                    55.4
2                    36.0  10895.49                    50.5
3                   120.0    524.61                    52.3
4                    60.0   1220.20                    39.6
...                   ...       ...                     ...
20035                36.0   1664.33                    50.5
20036                48.0   5595.50                    63.7
20037                24.0    958.36                    54.1
20038                 6.0  10841.73                    49.5
20039                36.0  42816.16                    60.0

       Farm_Productivity_Index  Climate_Risk_Index  Financial_Health_Index  \
0                         52.5                65.4                    57.7
1                         53.3                35.1                    70.3
2                         44.4                48.4                    50.3
3                         56.5                49.5                     0.0
4                         32.7                47.3                    59.6
...                        ...                 ...                     ...
20035                     61.4                52.8                    14.8
20036                     61.7                 0.0                    56.4
20037                     59.4                43.5                    65.8
20038                     50.7                19.5                    64.4
20039                     54.6                35.5                    38.4

       Loan_Affordability_Index  Asset_Strength_Index  Overall_Risk_Factor  \
0                          65.5                  48.5                 73.2
1                          72.2                  43.7                 52.0
2                          41.5                  46.8                 95.8
3                          13.1                  46.2                100.0
4                          79.5                  49.9                 65.8
...                         ...                   ...                  ...
20035                      19.1                   NaN                100.0
20036                      51.8                  59.4                 54.0
20037                      66.8                  51.1                 67.9
20038                       0.0                  41.7                 74.5
20039                      42.4                  49.8                 91.6

       Risk_Score
0            40.6
1            54.7
2            22.7
3            20.8
4            34.6
...           ...
20035        16.1
20036        31.8
20037        52.9
20038        38.5
20039        26.1

[20040 rows x 36 columns]

In [98]:
object_cols = df.select_dtypes(
    include=['object']
).columns.tolist()

print("Object columns:", len(object_cols))
print(object_cols)

Object columns: 24
['Farmer_ID', 'Application_Date', 'Gender', 'Education_Level', 'Marital_Status', 'State', 'District', 'Land_Ownership', 'Soil_Type', 'Irrigation_Availability', 'Primary_Crop', 'Secondary_Crop', 'Flood_Risk', 'Drought_Risk', 'Cyclone_Risk', 'Pest_Risk', 'Climate_Zone', 'Crop_Insurance', 'Government_Subsidy', 'MSP_Eligible', 'Tractor_Ownership', 'Previous_Default', 'Loan_Purpose', 'Loan_Status']

In [99]:
categorical_cols=df.select_dtypes(
    include=['object']
)
print(categorical_cols)

       Farmer_ID Application_Date  Gender   Education_Level Marital_Status  \
0      AGR117544       23-06-2023    Male  Higher Secondary        Married
1      AGR103888       02-10-2022  Female        Illiterate        Married
2      AGR112882       17-07-2024    Male         Secondary        Married
3      AGR108149       26-07-2024    Male     Post Graduate        Married
4      AGR115346       24-04-2022    Male           Primary        Married
...          ...              ...     ...               ...            ...
20035  AGR117677       21-04-2021    Male           Primary        Married
20036  AGR104023       17-06-2021    Male         Secondary        Married
20037  AGR107259       04-05-2022    Male  Higher Secondary        Married
20038  AGR103775       05-11-2023    Male          Graduate        Married
20039  AGR110137       05-12-2025    Male         Secondary        Married

                State            District Land_Ownership   Soil_Type  \
0              Kerala  Thiruvananthapuram         Shared    Laterite
1           Jharkhand          Hazaribagh         Leased         Red
2      Madhya Pradesh             Gwalior          Mixed         Red
3             Haryana              Karnal         Shared         NaN
4             Gujarat           Ahmedabad         Leased  Sandy Loam
...               ...                 ...            ...         ...
20035      Tamil Nadu                 NaN          Owned         Red
20036    Chhattisgarh                Durg         Shared        Clay
20037          Punjab            Ludhiana          Owned    Alluvial
20038     Maharashtra          Aurangabad          Mixed       Black
20039       Telangana             Khammam         Leased       Black

      Irrigation_Availability  ... Cyclone_Risk Pest_Risk        Climate_Zone  \
0                       False  ...         True       Low  Humid Sub-Tropical
1                        True  ...        False       Low  Humid Sub-Tropical
2                         NaN  ...        False    Medium           Semi-Arid
3                        True  ...        False    Medium           Semi-Arid
4                       False  ...         True       NaN           Semi-Arid
...                       ...  ...          ...       ...                 ...
20035                     NaN  ...        False      High           Semi-Arid
20036                    True  ...        False       Low           Semi-Arid
20037                     NaN  ...        False    Medium           Semi-Arid
20038                   False  ...        False      High           Semi-Arid
20039                    True  ...        False       Low                Arid

      Crop_Insurance Government_Subsidy MSP_Eligible Tractor_Ownership  \
0               True               True        False             False
1               True               True         True             False
2               True              False        False             False
3               True               True         True             False
4                NaN              False         True              True
...              ...                ...          ...               ...
20035          False              False         True             False
20036          False              False         True               NaN
20037           True               True         True             False
20038          False               True         True             False
20039          False               True         True             False

      Previous_Default     Loan_Purpose               Loan_Status
0                False              NaN  Approved with Conditions
1                False       Fertilizer                  Approved
2                 True  Processing Unit                  Rejected
3                False        Equipment                  Rejected
4                False       Fertilizer  Approved with Conditions
...                ...              ...                       ...
20035            False   Farm Expansion                  Rejected
20036            False   Farm Expansion                  Rejected
20037            False       Irrigation                  Approved
20038            False  Processing Unit  Approved with Conditions
20039             True     Cold Storage                  Rejected

[20040 rows x 24 columns]

In [100]:
print(df['Application_Date'].dtype)
print(df['Application_Date'].head(10).tolist())

object
['23-06-2023', '02-10-2022', '17-07-2024', '26-07-2024', '24-04-2022', '21-12-2025', '19-11-2024', '23-04-2023', '07-07-2022', '22-12-2023']

In [101]:
for cols in object_cols:
    values = df[col].dropna().unique()

    if set(values).issubset({True, False, 'True', 'False'}):
        print(col, "→ Boolean-like")

**Data type correction**

In [102]:
df['Application_Date']=pd.to_datetime(df['Application_Date'],errors='coerce')
print(df["Application_Date"].dtypes)

datetime64[ns]

/tmp/ipykernel_3628/3843223668.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Application_Date']=pd.to_datetime(df['Application_Date'],errors='coerce')

In [103]:
print(
    "Invalid dates:",
    df['Application_Date'].isna().sum()
)

Invalid dates: 0

In [104]:
boolean_like_columns=[]
for col in df.select_dtypes(include=['object']):
  values=set(df[col].dropna().unique())
  if values.issubset({True,False,'True','False'}):
    boolean_like_columns.append(col)
print("boolen columns :")
print(boolean_like_columns)
print(len(boolean_like_columns))

boolen columns :
['Irrigation_Availability', 'Flood_Risk', 'Drought_Risk', 'Cyclone_Risk', 'Crop_Insurance', 'Government_Subsidy', 'MSP_Eligible', 'Tractor_Ownership', 'Previous_Default']
9

checck target data type

In [105]:
print("Risk_Score:", df['Risk_Score'].dtype)
print("Loan_Status:", df['Loan_Status'].dtype)
print("Farmer_ID:", df['Farmer_ID'].dtype)

Risk_Score: float64
Loan_Status: object
Farmer_ID: object

check duplicates

In [106]:
print(df.duplicated().sum())

0

In [107]:
farmer_id_duplicate=df['Farmer_ID'].duplicated().sum()
print(farmer_id_duplicate)

0

In [108]:
print("unique farmer ids :",df['Farmer_ID'].unique())
print("total records",len(df))

unique farmer ids : ['AGR117544' 'AGR103888' 'AGR112882' ... 'AGR107259' 'AGR103775'
 'AGR110137']
total records 20040

In [109]:
check_duplicate_applications=df.duplicated(subset=df[['Farmer_ID','Application_Date']])
print("duplicate applications",check_duplicate_applications.sum())

duplicate applications 0

In [110]:
farmer_application_date=(df['Farmer_ID'].value_counts())
print(farmer_application_date[farmer_application_date>1])

Series([], Name: count, dtype: int64)

In [111]:
duplicate_without_id = df.duplicated(
    subset=[
        col for col in df.columns
        if col != 'Farmer_ID'
    ]
).sum()

print(
    "Rows duplicated excluding Farmer_ID:",
    duplicate_without_id
)

Rows duplicated excluding Farmer_ID: 40

In [112]:
duplicate_mask = df.duplicated(
    subset=[col for col in df.columns if col != 'Farmer_ID'],
    keep=False
)

duplicate_records = df[duplicate_mask].sort_values(
    by=[col for col in df.columns if col != 'Farmer_ID']
)

duplicate_records[['Farmer_ID', 'Application_Date', 'Loan_Status', 'Risk_Score']].head(20)

       Farmer_ID Application_Date               Loan_Status  Risk_Score
4923   AGR111191       2021-03-10                  Rejected        21.6
12090  AGR200003       2021-03-10                  Rejected        21.6
2859   AGR200016       2021-03-17                  Approved        46.3
6723   AGR111090       2021-03-17                  Approved        46.3
12623  AGR111988       2021-04-13                  Approved        45.3
15224  AGR200012       2021-04-13                  Approved        45.3
8064   AGR200024       2021-04-16  Approved with Conditions        37.8
12778  AGR111223       2021-04-16  Approved with Conditions        37.8
6919   AGR200013       2021-05-17                  Rejected        26.9
18842  AGR110266       2021-05-17                  Rejected        26.9
14301  AGR200000       2021-07-23                  Rejected        15.5
19762  AGR115831       2021-07-23                  Rejected        15.5
1716   AGR200004       2021-11-15                  Rejected        13.5
2537   AGR119062       2021-11-15                  Rejected        13.5
862    AGR101047       2021-11-17  Approved with Conditions        42.8
6521   AGR200032       2021-11-17  Approved with Conditions        42.8
10493  AGR200021       2021-11-19  Approved with Conditions        37.4
19070  AGR105147       2021-11-19  Approved with Conditions        37.4
7721   AGR200007       2021-12-03                  Rejected        31.8
7875   AGR107137       2021-12-03                  Rejected        31.8

In [113]:
print("Duplicate records to investigate:", duplicate_records.shape[0])

Duplicate records to investigate: 80

here 40 original and 40 duplicated recoreds, so we have to just remove the 40 duplicate one

In [114]:
duplicate_count = duplicate_without_id

print("Duplicate application profiles:", duplicate_count)

Duplicate application profiles: 40

In [115]:
df=df.drop_duplicates(subset=[col for col in df.columns if col!='Farmer_ID'],keep='first').reset_index(drop=True)

In [116]:
print("new shape",df.shape )
print("remaining duplicate profiles",df.duplicated(subset=[col for col in df.columns if col != 'Farmer_ID']).sum())

new shape (20000, 60)
remaining duplicate profiles 0

In [117]:
# # Columns used to identify duplicate application profiles
# duplicate_columns = [
#     col for col in df.columns
#     if col != 'Farmer_ID'
# ]

# # Check before removal
# print(
#     "Duplicate profiles before removal:",
#     df.duplicated(
#         subset=duplicate_columns,
#         keep='first'
#     ).sum()
# )

# # Remove only the second/redundant copies
# df = df.drop_duplicates(
#     subset=duplicate_columns,
#     keep='first'
# ).reset_index(drop=True)

# # Check after removal
# print("New shape:", df.shape)

# print(
#     "Duplicate profiles after removal:",
#     df.duplicated(
#         subset=duplicate_columns,
#         keep='first'
#     ).sum()
# )

In [118]:
y_classification=df['Loan_Status']
y_regression=df['Risk_Score']

x=df.drop(columns=['Loan_Status','Risk_Score'])

print("X shape:", x.shape)
print("Classification target:", y_classification.shape)
print("Regression target:", y_regression.shape)

X shape: (20000, 58)
Classification target: (20000,)
Regression target: (20000,)

for classification

In [119]:
from sklearn.model_selection import train_test_split
x_train_cls, x_test_cls, y_train_cls, y_test_cls = train_test_split(
    x,
    y_classification,
    test_size=0.3,
    random_state=42,
    stratify=y_classification
)

Split the temporary data into validation and test

In [120]:
x_train_cls, x_temp_cls, y_train_cls, y_temp_cls = train_test_split(
    x,
    y_classification,
    test_size=0.30,
    random_state=42,
    stratify=y_classification
)

In [121]:
x_val_cls, x_test_cls, y_val_cls, y_test_cls = train_test_split(
    x_temp_cls,
    y_temp_cls,
    test_size=0.50,
    random_state=42,
    stratify=y_temp_cls
)

In [122]:
print("Classification")
print("----------------")
print("Training   :", x_train_cls.shape)
print("Validation :", x_val_cls.shape)
print("Testing    :", x_test_cls.shape)

Classification
----------------
Training   : (14000, 58)
Validation : (3000, 58)
Testing    : (3000, 58)

In [123]:
print("\nTarget distribution:")
print("Training:")
print(y_train_cls.value_counts(normalize=True))

print("\nValidation:")
print(y_val_cls.value_counts(normalize=True))

print("\nTesting:")
print(y_test_cls.value_counts(normalize=True))

Target distribution:
Training:
Loan_Status
Approved with Conditions    0.413143
Rejected                    0.303929
Approved                    0.282929
Name: proportion, dtype: float64

Validation:
Loan_Status
Approved with Conditions    0.413333
Rejected                    0.304000
Approved                    0.282667
Name: proportion, dtype: float64

Testing:
Loan_Status
Approved with Conditions    0.413
Rejected                    0.304
Approved                    0.283
Name: proportion, dtype: float64

splitting for regression

In [124]:
x_train_reg, x_test_reg , y_train_reg, y_test_reg = train_test_split(
    x,
    y_regression,
    test_size=0.3,
    random_state=42
)

In [125]:
x_val_reg, x_test_reg , y_val_reg , y_test_reg = train_test_split(
    x_test_reg,
    y_test_reg,
    test_size=0.5,
    random_state=42,

)

In [126]:
print("Regression")
print("----------------")
print("Training   :", x_train_reg.shape)
print("Validation :", x_val_reg.shape)
print("Testing    :", x_test_reg.shape)

Regression
----------------
Training   : (14000, 58)
Validation : (3000, 58)
Testing    : (3000, 58)

handling missing values

In [127]:
print("missing values in training dataset :")
print(x_train_cls.isna().sum())

missing values in training dataset :
Farmer_ID                                 0
Application_Date                          0
Age                                     621
Gender                                  647
Education_Level                         444
Marital_Status                          830
Family_Size                             412
Dependents                              359
Farming_Experience_Years                521
State                                   380
District                                442
Farm_Size_Acres                         508
Land_Ownership                          748
Soil_Type                               767
Soil_Quality_Index                      801
Irrigation_Availability                 651
Primary_Crop                            506
Secondary_Crop                          524
Annual_Rainfall_mm                      289
Average_Temperature_C                   645
Humidity_Percent                        433
Flood_Risk                              415
Drought_Risk                            512
Cyclone_Risk                            828
Pest_Risk                               340
Weather_Risk_Index                      434
Climate_Zone                            716
Average_Yield_Last3Years_TonsPerAcre    789
Crop_Insurance                          874
Government_Subsidy                      608
MSP_Eligible                            347
Annual_Farm_Income                      694
Annual_Farm_Expenses                    659
Tractor_Ownership                       441
Farm_Equipment_Value                    719
Livestock_Count                         272
Asset_Value                             275
Liability_Value                         685
Savings                                 553
Bank_Balance                            384
Credit_Score                            467
Existing_Loan_Count                     529
Existing_Loan_Amount                    522
Previous_Default                        391
Repayment_History_Score                 567
Debt_to_Income_Ratio                    563
Loan_Amount_Requested                   726
Loan_Purpose                            679
Interest_Rate_Percent                   645
Loan_Tenure_Months                      704
EMI                                     760
Income_Stability_Index                  523
Farm_Productivity_Index                 667
Climate_Risk_Index                      420
Financial_Health_Index                  477
Loan_Affordability_Index                378
Asset_Strength_Index                    708
Overall_Risk_Factor                     559
dtype: int64

In [128]:
print("missing values in testing dataset :")
print(x_test_cls.isna().sum())
print("Shape of testing dataset :", x_test_cls.shape)

missing values in testing dataset :
Farmer_ID                                 0
Application_Date                          0
Age                                     139
Gender                                  107
Education_Level                          80
Marital_Status                          147
Family_Size                              89
Dependents                               62
Farming_Experience_Years                129
State                                    81
District                                116
Farm_Size_Acres                         103
Land_Ownership                          168
Soil_Type                               170
Soil_Quality_Index                      182
Irrigation_Availability                 128
Primary_Crop                            111
Secondary_Crop                          129
Annual_Rainfall_mm                       74
Average_Temperature_C                   173
Humidity_Percent                         71
Flood_Risk                              104
Drought_Risk                            108
Cyclone_Risk                            189
Pest_Risk                                84
Weather_Risk_Index                      105
Climate_Zone                            154
Average_Yield_Last3Years_TonsPerAcre    172
Crop_Insurance                          153
Government_Subsidy                      116
MSP_Eligible                             80
Annual_Farm_Income                      175
Annual_Farm_Expenses                    145
Tractor_Ownership                        90
Farm_Equipment_Value                    158
Livestock_Count                          67
Asset_Value                              59
Liability_Value                         152
Savings                                 111
Bank_Balance                             83
Credit_Score                             98
Existing_Loan_Count                     106
Existing_Loan_Amount                    111
Previous_Default                         89
Repayment_History_Score                 119
Debt_to_Income_Ratio                    105
Loan_Amount_Requested                   139
Loan_Purpose                            164
Interest_Rate_Percent                   127
Loan_Tenure_Months                      144
EMI                                     175
Income_Stability_Index                  109
Farm_Productivity_Index                 136
Climate_Risk_Index                      105
Financial_Health_Index                  107
Loan_Affordability_Index                 75
Asset_Strength_Index                    157
Overall_Risk_Factor                     115
dtype: int64
Shape of testing dataset : (3000, 58)

In [129]:
print("missing values in validation dataset :")
print(x_val_cls.isna().sum())
print("Shape of validation dataset :", x_val_cls.shape)

missing values in validation dataset :
Farmer_ID                                 0
Application_Date                          0
Age                                     140
Gender                                  142
Education_Level                          84
Marital_Status                          172
Family_Size                              84
Dependents                               70
Farming_Experience_Years                123
State                                    93
District                                103
Farm_Size_Acres                         125
Land_Ownership                          158
Soil_Type                               149
Soil_Quality_Index                      150
Irrigation_Availability                 126
Primary_Crop                             89
Secondary_Crop                           95
Annual_Rainfall_mm                       63
Average_Temperature_C                   154
Humidity_Percent                         81
Flood_Risk                               92
Drought_Risk                            100
Cyclone_Risk                            170
Pest_Risk                                87
Weather_Risk_Index                       91
Climate_Zone                            156
Average_Yield_Last3Years_TonsPerAcre    161
Crop_Insurance                          160
Government_Subsidy                      126
MSP_Eligible                             61
Annual_Farm_Income                      137
Annual_Farm_Expenses                    138
Tractor_Ownership                        92
Farm_Equipment_Value                    152
Livestock_Count                          61
Asset_Value                              70
Liability_Value                         161
Savings                                 131
Bank_Balance                             76
Credit_Score                             86
Existing_Loan_Count                     117
Existing_Loan_Amount                    124
Previous_Default                         80
Repayment_History_Score                 114
Debt_to_Income_Ratio                    113
Loan_Amount_Requested                   151
Loan_Purpose                            154
Interest_Rate_Percent                   162
Loan_Tenure_Months                      154
EMI                                     142
Income_Stability_Index                  113
Farm_Productivity_Index                 173
Climate_Risk_Index                      101
Financial_Health_Index                   95
Loan_Affordability_Index                 73
Asset_Strength_Index                    156
Overall_Risk_Factor                     115
dtype: int64
Shape of validation dataset : (3000, 58)

Find which columns have missing values

In [130]:
missing_cols = x_train_cls.columns[
    x_train_cls.isnull().sum() > 0
]

print("Columns with missing values:")
print(missing_cols.tolist())

Columns with missing values:
['Age', 'Gender', 'Education_Level', 'Marital_Status', 'Family_Size', 'Dependents', 'Farming_Experience_Years', 'State', 'District', 'Farm_Size_Acres', 'Land_Ownership', 'Soil_Type', 'Soil_Quality_Index', 'Irrigation_Availability', 'Primary_Crop', 'Secondary_Crop', 'Annual_Rainfall_mm', 'Average_Temperature_C', 'Humidity_Percent', 'Flood_Risk', 'Drought_Risk', 'Cyclone_Risk', 'Pest_Risk', 'Weather_Risk_Index', 'Climate_Zone', 'Average_Yield_Last3Years_TonsPerAcre', 'Crop_Insurance', 'Government_Subsidy', 'MSP_Eligible', 'Annual_Farm_Income', 'Annual_Farm_Expenses', 'Tractor_Ownership', 'Farm_Equipment_Value', 'Livestock_Count', 'Asset_Value', 'Liability_Value', 'Savings', 'Bank_Balance', 'Credit_Score', 'Existing_Loan_Count', 'Existing_Loan_Amount', 'Previous_Default', 'Repayment_History_Score', 'Debt_to_Income_Ratio', 'Loan_Amount_Requested', 'Loan_Purpose', 'Interest_Rate_Percent', 'Loan_Tenure_Months', 'EMI', 'Income_Stability_Index', 'Farm_Productivity_Index', 'Climate_Risk_Index', 'Financial_Health_Index', 'Loan_Affordability_Index', 'Asset_Strength_Index', 'Overall_Risk_Factor']

In [131]:
print(x_train_cls[missing_cols].isnull().sum())

Age                                     621
Gender                                  647
Education_Level                         444
Marital_Status                          830
Family_Size                             412
Dependents                              359
Farming_Experience_Years                521
State                                   380
District                                442
Farm_Size_Acres                         508
Land_Ownership                          748
Soil_Type                               767
Soil_Quality_Index                      801
Irrigation_Availability                 651
Primary_Crop                            506
Secondary_Crop                          524
Annual_Rainfall_mm                      289
Average_Temperature_C                   645
Humidity_Percent                        433
Flood_Risk                              415
Drought_Risk                            512
Cyclone_Risk                            828
Pest_Risk                               340
Weather_Risk_Index                      434
Climate_Zone                            716
Average_Yield_Last3Years_TonsPerAcre    789
Crop_Insurance                          874
Government_Subsidy                      608
MSP_Eligible                            347
Annual_Farm_Income                      694
Annual_Farm_Expenses                    659
Tractor_Ownership                       441
Farm_Equipment_Value                    719
Livestock_Count                         272
Asset_Value                             275
Liability_Value                         685
Savings                                 553
Bank_Balance                            384
Credit_Score                            467
Existing_Loan_Count                     529
Existing_Loan_Amount                    522
Previous_Default                        391
Repayment_History_Score                 567
Debt_to_Income_Ratio                    563
Loan_Amount_Requested                   726
Loan_Purpose                            679
Interest_Rate_Percent                   645
Loan_Tenure_Months                      704
EMI                                     760
Income_Stability_Index                  523
Farm_Productivity_Index                 667
Climate_Risk_Index                      420
Financial_Health_Index                  477
Loan_Affordability_Index                378
Asset_Strength_Index                    708
Overall_Risk_Factor                     559
dtype: int64

In [132]:
numeric_cols = x_train_cls.select_dtypes(
    include=['int64', 'float64']
).columns

categorical_cols = x_train_cls.select_dtypes(
    include=['object']
).columns

print("Numerical columns:", len(numeric_cols))
print("Categorical columns:", len(categorical_cols))

Numerical columns: 35
Categorical columns: 22

same median for validation and testing set

In [133]:
numeric_cols = x_train_cls.select_dtypes(
    include=['int64', 'float64']
).columns

for col in numeric_cols:

    median_value = x_train_cls[col].median()

    x_train_cls[col] = x_train_cls[col].fillna(median_value)
    x_val_cls[col] = x_val_cls[col].fillna(median_value)
    x_test_cls[col] = x_test_cls[col].fillna(median_value)

In [134]:
for col in categorical_cols:

    x_train_cls[col] = x_train_cls[col].fillna('Unknown')
    x_val_cls[col] = x_val_cls[col].fillna('Unknown')
    x_test_cls[col] = x_test_cls[col].fillna('Unknown')

In [135]:
print("Training missing:", x_train_cls.isnull().sum().sum())
print("Validation missing:", x_val_cls.isnull().sum().sum())
print("Testing missing:", x_test_cls.isnull().sum().sum())

Training missing: 0
Validation missing: 0
Testing missing: 0

remove farmer id and application date

In [136]:
print("FamerID :",'FamerID' in x_train_cls.columns)
print("Application_Date :",'Application_Date' in x_train_cls.columns)

FamerID : False
Application_Date : True

In [137]:
drop_cols = ['Farmer_ID', 'Application_Date']

x_train_cls = x_train_cls.drop(columns=drop_cols, errors='ignore')
x_val_cls = x_val_cls.drop(columns=drop_cols, errors='ignore')
x_test_cls = x_test_cls.drop(columns=drop_cols, errors='ignore')

handling missing values

In [138]:
numeric_cols = x_train_cls.select_dtypes(
    include=['int64', 'float64']
).columns

for col in numeric_cols:

    median_value = x_train_cls[col].median()

    x_train_cls[col] = x_train_cls[col].fillna(median_value)
    x_val_cls[col] = x_val_cls[col].fillna(median_value)
    x_test_cls[col] = x_test_cls[col].fillna(median_value)

In [139]:
categorical_cols = x_train_cls.select_dtypes(
    include=['object']
).columns

for col in categorical_cols:

    x_train_cls[col] = x_train_cls[col].fillna('Unknown')
    x_val_cls[col] = x_val_cls[col].fillna('Unknown')
    x_test_cls[col] = x_test_cls[col].fillna('Unknown')

encoding

In [140]:
from sklearn.preprocessing import OneHotEncoder

categorical_cols = x_train_cls.select_dtypes(
    include='object'
).columns

# Convert all categorical columns to string type before encoding
for col in categorical_cols:
    x_train_cls[col] = x_train_cls[col].astype(str)
    x_val_cls[col] = x_val_cls[col].astype(str)
    x_test_cls[col] = x_test_cls[col].astype(str)

encoder = OneHotEncoder(
    handle_unknown='ignore',
    sparse_output=False
)

x_train_encoded = encoder.fit_transform(
    x_train_cls[categorical_cols]
)

x_val_encoded = encoder.transform(
    x_val_cls[categorical_cols]
)

x_test_encoded = encoder.transform(
    x_test_cls[categorical_cols]
)

In [141]:
print("Categorical columns:", len(categorical_cols))
print("Encoded training shape:", x_train_encoded.shape)

Categorical columns: 21
Encoded training shape: (14000, 245)

In [142]:
x_val_encoded=encoder.transform(x_val_cls[categorical_cols])
x_test_encoded=encoder.transform(x_test_cls[categorical_cols])

In [143]:
x_train_reg = x_train_reg.drop(columns=drop_cols, errors='ignore')
x_val_reg = x_val_reg.drop(columns=drop_cols, errors='ignore')
x_test_reg = x_test_reg.drop(columns=drop_cols, errors='ignore')

Encode the numerical columns separately

In [144]:
numerical_cols = x_train_cls.select_dtypes(
    exclude='object'
).columns

In [145]:
numerical_cols = x_train_cls.select_dtypes(
    exclude='object'
).columns

x_train_final = np.hstack([
    x_train_cls[numerical_cols].values,
    x_train_encoded
])

x_val_final = np.hstack([
    x_val_cls[numerical_cols].values,
    x_val_encoded
])

x_test_final = np.hstack([
    x_test_cls[numerical_cols].values,
    x_test_encoded
])

In [146]:
print("Training :", x_train_final.shape)
print("Validation:", x_val_final.shape)
print("Testing :", x_test_final.shape)

Training : (14000, 280)
Validation: (3000, 280)
Testing : (3000, 280)

In [147]:
print("Original training shape:", x_train_cls.shape)

print("Categorical encoded shape:", x_train_encoded.shape)

print("Numerical columns:", len(numerical_cols))

Original training shape: (14000, 56)
Categorical encoded shape: (14000, 245)
Numerical columns: 35

In [148]:
print("Final shape:", x_train_final.shape)

Final shape: (14000, 280)

saving the files before encoding for tree based models

In [149]:
feature_names = (
    list(numerical_cols) +
    list(encoder.get_feature_names_out(categorical_cols))
)

x_train_final_df = pd.DataFrame(
    x_train_final,
    columns=feature_names
)

x_val_final_df = pd.DataFrame(
    x_val_final,
    columns=feature_names
)

x_test_final_df = pd.DataFrame(
    x_test_final,
    columns=feature_names
)

In [150]:
print(x_train_final_df.shape)
print(x_val_final_df.shape)
print(x_test_final_df.shape)

(14000, 280)
(3000, 280)
(3000, 280)

In [151]:
x_train_final_df.to_csv(
    '/content/drive/MyDrive/X_train_encoded.csv',
    index=False
)

x_val_final_df.to_csv(
    '/content/drive/MyDrive/X_val_encoded.csv',
    index=False
)

x_test_final_df.to_csv(
    '/content/drive/MyDrive/X_test_encoded.csv',
    index=False
)

print("All files saved to Google Drive")

All files saved to Google Drive

In [152]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train_final_df)

x_val_scaled = scaler.transform(x_val_final_df)

x_test_scaled = scaler.transform(x_test_final_df)

In [153]:
x_train_scaled_df = pd.DataFrame(
    x_train_scaled,
    columns=x_train_final_df.columns
)

x_val_scaled_df = pd.DataFrame(
    x_val_scaled,
    columns=x_val_final_df.columns
)

x_test_scaled_df = pd.DataFrame(
    x_test_scaled,
    columns=x_test_final_df.columns
)

In [154]:
print("Train:", x_train_scaled_df.shape)
print("Validation:", x_val_scaled_df.shape)
print("Test:", x_test_scaled_df.shape)

Train: (14000, 280)
Validation: (3000, 280)
Test: (3000, 280)

In [155]:
x_train_scaled_df.to_csv(
    '/content/drive/MyDrive/X_train_scaled.csv',
    index=False
)

x_val_scaled_df.to_csv(
    '/content/drive/MyDrive/X_val_scaled.csv',
    index=False
)

x_test_scaled_df.to_csv(
    '/content/drive/MyDrive/X_test_scaled.csv',
    index=False
)

print("Scaled datasets saved successfully!")

Scaled datasets saved successfully!

In [156]:
y_classification=df['Loan_Status']
y_regression=df['Risk_Score']
print(y_classification.shape)
print(y_regression.shape)

(20000,)
(20000,)

In [157]:
y_classification.to_csv(
    '/content/drive/MyDrive/y_classification.csv',
    index=False
)

y_regression.to_csv(
    '/content/drive/MyDrive/y_regression.csv',
    index=False
)

In [158]:
from sklearn.model_selection import train_test_split

# Classification target
y_classification = df['Loan_Status']

# 70% Training, 30% temporary
y_train_cls, y_temp_cls = train_test_split(
    y_classification,
    test_size=0.30,
    random_state=42,
    stratify=y_classification
)

# Split temporary 30% into 15% validation + 15% testing
y_val_cls, y_test_cls = train_test_split(
    y_temp_cls,
    test_size=0.50,
    random_state=42,
    stratify=y_temp_cls
)

In [159]:
print("Classification targets:")
print("Train:", y_train_cls.shape)
print("Validation:", y_val_cls.shape)
print("Test:", y_test_cls.shape)

Classification targets:
Train: (14000,)
Validation: (3000,)
Test: (3000,)

In [160]:
# Regression target
y_regression = df['Risk_Score']

# 70% Training, 30% temporary
y_train_reg, y_temp_reg = train_test_split(
    y_regression,
    test_size=0.30,
    random_state=42
)

# Split temporary 30% into 15% validation + 15% testing
y_val_reg, y_test_reg = train_test_split(
    y_temp_reg,
    test_size=0.50,
    random_state=42
)

In [161]:
print("Regression targets:")
print("Train:", y_train_reg.shape)
print("Validation:", y_val_reg.shape)
print("Test:", y_test_reg.shape)

Regression targets:
Train: (14000,)
Validation: (3000,)
Test: (3000,)

In [162]:
y_train_cls.to_csv(
    '/content/drive/MyDrive/y_train_classification.csv',
    index=False
)

y_val_cls.to_csv(
    '/content/drive/MyDrive/y_val_classification.csv',
    index=False
)

y_test_cls.to_csv(
    '/content/drive/MyDrive/y_test_classification.csv',
    index=False
)


y_train_reg.to_csv(
    '/content/drive/MyDrive/y_train_regression.csv',
    index=False
)

y_val_reg.to_csv(
    '/content/drive/MyDrive/y_val_regression.csv',
    index=False
)

y_test_reg.to_csv(
    '/content/drive/MyDrive/y_test_regression.csv',
    index=False
)

print("All target files saved successfully!")

All target files saved successfully!

In [163]:
print(x_train_cls.isnull().sum())

Age                                     0
Gender                                  0
Education_Level                         0
Marital_Status                          0
Family_Size                             0
Dependents                              0
Farming_Experience_Years                0
State                                   0
District                                0
Farm_Size_Acres                         0
Land_Ownership                          0
Soil_Type                               0
Soil_Quality_Index                      0
Irrigation_Availability                 0
Primary_Crop                            0
Secondary_Crop                          0
Annual_Rainfall_mm                      0
Average_Temperature_C                   0
Humidity_Percent                        0
Flood_Risk                              0
Drought_Risk                            0
Cyclone_Risk                            0
Pest_Risk                               0
Weather_Risk_Index                      0
Climate_Zone                            0
Average_Yield_Last3Years_TonsPerAcre    0
Crop_Insurance                          0
Government_Subsidy                      0
MSP_Eligible                            0
Annual_Farm_Income                      0
Annual_Farm_Expenses                    0
Tractor_Ownership                       0
Farm_Equipment_Value                    0
Livestock_Count                         0
Asset_Value                             0
Liability_Value                         0
Savings                                 0
Bank_Balance                            0
Credit_Score                            0
Existing_Loan_Count                     0
Existing_Loan_Amount                    0
Previous_Default                        0
Repayment_History_Score                 0
Debt_to_Income_Ratio                    0
Loan_Amount_Requested                   0
Loan_Purpose                            0
Interest_Rate_Percent                   0
Loan_Tenure_Months                      0
EMI                                     0
Income_Stability_Index                  0
Farm_Productivity_Index                 0
Climate_Risk_Index                      0
Financial_Health_Index                  0
Loan_Affordability_Index                0
Asset_Strength_Index                    0
Overall_Risk_Factor                     0
dtype: int64